exports.Constants =
        Object.freeze({
                StudentId: 0,
                CoachName: 1,
                FirstGen: 2,
                Race: 3,
                Disability: 4,
                Classification: 5,
                SevenTargetSchools: 6,
                NotifiedStudent: 7,
                ScholarshipMatchingComplete: 8,
                ScholarshipEssay: 9,
                ScholarshipDeadlines: 10,
                ScholarshipEssay3: 11,
                ReviewOfEssay: 12,
                CollegeApplicationDeadLines: 13,
                CompletedFafsa: 14,
                AdmissionDeadlines: 15,
                Rejected: 16,
                Waitlisted: 17,
                Accepted: 18,
                CollegePacketComplete: 19,
                CoachFinalReview: 20,
                LOR: 21,
                Resume: 22,
                Interview: 23,
                Award: 24
        });