exports.Fields = [      
"Student ID",
"Coach Name",
"1st Generation?",
"Race",
"Disability?",
"Classification",
"7 Target Schools Completed?",
"Notified Student?",
"Scholarship Matching Complete?",
"Scholarship Essay",
"Scholarship Deadlines",
"Scholarship Essay #3",
"Review of Essay?",
"College Application Deadlines?",
"Completed FAFSA?",
"Admission Deadlines",
"Rejected?",
"Waitlisted?",
"Accepted ?",
"College Packet Complete?",
"Coach Final Review",
"LOR",
"Resume",
"Interview?",
"Scholarship Awarded",
]